version: '3'

tasks:
  default:
    cmds:
      - task: run

  build:
    cmds:
      - odin build sgrep -collection:dependencies=dependencies -out=bin/sgrep
    aliases:
      - b
    silent: true
    sources:
      - './sgrep/**/*.odin'
    generates:
      - bin/sgrep

  sgrep:
    deps:
      - build
    cmds:
      - bin/sgrep {{.CLI_ARGS}}
    silent: true
    method: none
  
  run:
    cmds:
      - odin run sgrep -collection:dependencies=dependencies -out:bin/sgrep -o:speed -- {{.CLI_ARGS}}
    aliases:
      - r
    method: none
    silent: true
    sources:
      - '**/*.odin'

interval: 250ms
